name: mewnu_storybook
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.19.0-406.0.dev <3.0.0'

dependencies:
  asgard_core:
    path: ../asgard_core
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  widgetbook2: ^2.4.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  widgetbook_generator:
  widgetbook_annotation:

flutter:
  uses-material-design: true