name: test_utils
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter_test:
    sdk: flutter
  flutter:
    sdk: flutter
  mockito: ^5.0.17

dev_dependencies:
  flutter_lints: ^1.0.0





flutter:

  
  
  
  
  
  
  
  
  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
