name: asgard
description: A new Flutter project.



publish_to: 'none' 











version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"







dependencies:
  asgard_core:
    path: ../asgard_core
  flutter:
    sdk: flutter


  
  
  cupertino_icons: ^1.0.2
  equatable: ^2.0.3
  provider: ^6.0.2
  flutter_svg: ^1.0.3
  go_router: ^7.1.1
  # collection: ^1.16.0

dev_dependencies:
  test_utils:
    path: ../test_utils
  flutter_test:
    sdk: flutter

  
  
  
  
  
  flutter_lints: ^1.0.0

flutter:

  
  
  
  uses-material-design: true

  
  assets:
    - assets/images/

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
